name: Tests (pytest)

on:
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize
    paths:
      - "**.csv"
      - "**.npy"
      - "**.out"
      - "**.pkl"
      - "**.png"
      - "**.py"
      - "**.toml"
      - "**.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        # TopoStats can't support Python >= 3.12 due to an issue with dependency Topoly (see
        # https://github.com/AFM-SPM/TopoStats/issues/927)
        python-version: ["3.10", "3.11"]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Install and setup uv with python
        uses: astral-sh/setup-uv@v10.0.1
        with:
          activate-environment: true
          python-version: ${{ matrix.python-version }}
      - name: Install package dependencies in activated environment
        shell: bash
        run: |
          uv sync --locked --all-extras --dev
      - name: Pytest
        run: |
          uv run pytest --cov=src --cov-branch --numprocesses=logical tests
      - name: Determine coverage
        if: runner.os == 'Linux'
        shell: bash
        run: |
          source .venv/bin/activate
          coverage xml
      - name: Upload coverage to Codecov
        if: runner.os == 'Linux'
        uses: codecov/codecov-action@v7
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 5
